# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='current_price',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='game',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='header_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='original_price',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='seller',
            field=models.CharField(blank=True, choices=[('g2a', 'G2a'), ('king', 'Kinguin'), ('gamestop', 'Gamestop')], max_length=50, null=True),
        ),
    ]
