# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20171021_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='buy_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
