# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('search_url', models.URLField()),
                ('logo_url', models.URLField()),
                ('rating', models.CharField(max_length=5)),
            ],
        ),
    ]
