# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='ref_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
