# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_seller_ref_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
