# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('g2a_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('g2a_url', models.URLField(blank=True, null=True, verbose_name='G2a URL')),
                ('kinguin_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('kinguin_url', models.URLField(blank=True, null=True, verbose_name='Kinguin URL')),
                ('greenman_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('greenman_url', models.URLField(blank=True, null=True, verbose_name='Greenman URL')),
                ('gamestop_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('gamestop_url', models.URLField(blank=True, null=True, verbose_name='Gamestop URL')),
            ],
        ),
        migrations.CreateModel(
            name='GameImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='games.GameImages'),
        ),
    ]
