# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='images',
        ),
        migrations.AddField(
            model_name='game',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.GameImages'),
        ),
    ]
