# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='community_reddit',
            field=models.URLField(blank=True, null=True, verbose_name='Reddit community urls'),
        ),
    ]
