# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170828_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='images',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.DeleteModel(
            name='GameImages',
        ),
    ]
