# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='kinguin_price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
