# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20171017_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='g2a_price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
